# Generated by Django 3.1.4 on 2021-12-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Career', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('profile', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('greetings', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
