# Generated by Django 3.1.4 on 2021-12-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MANFRED', '0004_auto_20211208_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topic'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='Title',
        ),
    ]
