# Generated by Django 3.1.4 on 2021-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MANFRED', '0005_auto_20211208_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='home',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
