# Generated by Django 3.1.4 on 2021-12-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wensday', 'Wensday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='Supper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast', models.ManyToManyField(related_name='breakfast', to='MENU.Breakfast')),
                ('Day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MENU.days')),
                ('Lunch', models.ManyToManyField(related_name='lunch', to='MENU.Lunch')),
                ('Supper', models.ManyToManyField(related_name='supper', to='MENU.Supper')),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'ordering': ('id',),
            },
        ),
    ]
