# Generated by Django 3.1.4 on 2021-12-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MENU', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakfast',
            options={'verbose_name_plural': 'Breakfast'},
        ),
        migrations.AlterModelOptions(
            name='days',
            options={'ordering': ('id',), 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='lunch',
            options={'verbose_name_plural': 'Lunch'},
        ),
        migrations.AlterModelOptions(
            name='supper',
            options={'verbose_name_plural': 'Supper'},
        ),
    ]
